### ISSUE TITLE
Hitting uploads per minute quota

### ISSUE THREAD

**Issue by jone** [int128/gpup#13]
Hey there

When uploading large amounts of photos at once I'm hitting a quota:
```
2018/09/15 19:17:26 Uploading IMG_6427.jpg
2018/09/15 19:17:26 Error while uploading /Users/jone/Pictures/Photos Library.photoslibrary/Masters/2009/07/18/20090718-190427/IMG_6663.jpg: Could not upload /Users/jone/Pictures/Photos Library.photoslibrary/Masters/2009/07/18/20090718-190427/IMG_6663.jpg: status 400: {
  "code": 3,
  "message": "Insufficient tokens for quota \u0027photoslibrary.googleapis.com/upload_requests\u0027 and limit \u0027UploadsPerMinute\u0027 of service \u0027photoslibrary.googleapis.com\u0027 for consumer \u0027project_number:638493XXXXX\u0027."
}
```

Unfortunately I'm not that familiar with Go, but as far as I could interpret the code I suspect that gpup does not detect that problem and retry uploading this particular image: the response status is 400, but retry does only work with codes of 500 and greater.
I guess there is no way to circumvent the quota, with another type of account, right?
Or did I do something wrong?

I'd suggest to implement a sleep / retry strategy, but I'm not familiar enough with the Go environment to do that on may own.

**Comment by pacoorozco** [comment]
Hi @jone 

This is the [rate limit that Google is applying to Google Photos API](https://developers.google.com/photos/library/guides/api-limits-quotas), so It's difficult to avoid this issue.

> *General quota limit*
The quota limit for requests to the Library API is 10,000 requests per project per day. Requests to access media bytes (like loading a photo or video) are not counted against the limit.

> *Exceeding quota limits*
If the quota of requests to the Library API is exceeded, the API returns an error code 429 and a message that the project has exceeded the quota. For more information, see the Terms of Service.

**Comment by felciano** [comment]
@pacoorozco is there a straightforward way to restart an upload sequence that failed due to this quota error? Or is there a way to get gpup to avoid uploading media that was previously successfully uploaded (e.g. via checksum comparison btw local media file and the remote one)?

**Comment by pacoorozco** [comment]
Hi @felciano 

I'm using [this script](https://github.com/pacoorozco/dotfiles/blob/master/bin/upload_to_Google_Photos.sh) that keeps track of uploaded files, so I can resume it later or I can do periodic syncs.

Feedback is welcomed :-D

**Comment by endzyme** [comment]
https://github.com/int128/gpup/pull/46 (modifying the support for more retry-ability could be done like so). Either with status code or with status code and error message.
